service: nodeless
  - configValidationMode: error

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  #tamanho de memória que ira utilizar
  memorySize: 256
  # Permissões que a função vai poder utilizar, quais serviços.
  iam:
    role:
      statements:
        - Effect: Allow
          Action: # Permitido buscar no S3 um objeto e também salvar
            - s3:GetObject
            - s3:PutObject
          Resouce:  # Em qual Bucket do S3 está permitido operar, depois dos 3 pontos definimos qual bucket. * indica em todos
            - "arn:aws:s3:::*"

functions:
  optimize: #nome da função para invocar na CLI
    handler: optimize.handle
    environment: #passando qual o bucket vamos declarar
      bucket: serverless
    events: # Eventos que iremos ouvir
      - s3:
          bucket: serverless
          event:  s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg

      - s3:
          bucket: serverless
          event:  s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
      